// Stubbed re-engagement queue. All values are illustrative for the prototype.

const STAGE = {
  not_started:      { label: "Not started",     tone: "slate" },
  staff_sent:       { label: "Staff sent",      tone: "clay"  },
  ai_working:       { label: "AI working",      tone: "teal"  },
  awaiting_patient: { label: "Awaiting reply",  tone: "amber" },
  needs_you:        { label: "Needs you",       tone: "red"   },
  booked:           { label: "Booked",          tone: "teal-solid" },
  closed:           { label: "Closed",          tone: "slate" },
};

// reasons for a "needs you" handoff — only 3, kept narrow on purpose
const HANDOFF = {
  off_script:    { label: "Off-script question", tone: "amber" },
  no_slot:       { label: "No matching slot",    tone: "amber" },
  asked_human:   { label: "Asked for human",     tone: "amber" },
};

const PATIENTS = [
  {
    id: "p-rachel",
    name: "Rachel Moore",
    initials: "RM",
    phoneMask: "(•••) •••-2118",
    overdue: "11 mo",
    overdueDays: 334,
    lastVisit: "Jun 12, 2025",
    reason: "Hygiene recall",
    stage: "ai_working",
    nextStep: "Confirming time",
    activity: "Skrypt AI proposed 2 slots · 14m ago",
    value: 850,
    pinned: true,
  },
  {
    id: "p-tobias",
    name: "Tobias Grant",
    initials: "TG",
    phoneMask: "(•••) •••-0461",
    overdue: "7 mo",
    overdueDays: 213,
    lastVisit: "Oct 3, 2025",
    reason: "Treatment plan: 2 fillings",
    stage: "needs_you",
    handoff: "off_script",
    nextStep: "Reply about insurance",
    activity: "Patient asked an insurance Q · 41m ago",
    value: 1200,
    pinned: true,
  },
  {
    id: "p-eve",
    name: "Eve Walsh",
    initials: "EW",
    phoneMask: "(•••) •••-7732",
    overdue: "14 mo",
    overdueDays: 426,
    lastVisit: "Mar 1, 2025",
    reason: "Hygiene recall",
    stage: "not_started",
    nextStep: "Start outreach",
    activity: "—",
    value: 400,
  },
  {
    id: "p-marcus",
    name: "Marcus Liu",
    initials: "ML",
    phoneMask: "(•••) •••-3308",
    overdue: "9 mo",
    overdueDays: 274,
    lastVisit: "Aug 5, 2025",
    reason: "Crown follow-up",
    stage: "awaiting_patient",
    nextStep: "Awaiting reply",
    activity: "Skrypt AI sent a nudge · 2h ago",
    value: 2200,
  },
  {
    id: "p-priya",
    name: "Priya Shah",
    initials: "PS",
    phoneMask: "(•••) •••-9912",
    overdue: "6 mo",
    overdueDays: 184,
    lastVisit: "Nov 11, 2025",
    reason: "Hygiene recall",
    stage: "booked",
    nextStep: "Booked Tue Nov 18 · 2:30pm",
    activity: "Skrypt AI booked the slot · yesterday",
    value: 280,
  },
  {
    id: "p-james",
    name: "James Okafor",
    initials: "JO",
    phoneMask: "(•••) •••-1042",
    overdue: "8 mo",
    overdueDays: 244,
    lastVisit: "Sep 8, 2025",
    reason: "Hygiene recall",
    stage: "staff_sent",
    nextStep: "Awaiting first reply",
    activity: "Maria sent the opener · 22m ago",
    value: 280,
  },
  {
    id: "p-anya",
    name: "Anya Petrov",
    initials: "AP",
    phoneMask: "(•••) •••-5519",
    overdue: "12 mo",
    overdueDays: 366,
    lastVisit: "May 14, 2025",
    reason: "Treatment plan: implant consult",
    stage: "needs_you",
    handoff: "no_slot",
    nextStep: "Override the schedule",
    activity: "No slot fit patient's window · 3h ago",
    value: 3400,
  },
  {
    id: "p-derek",
    name: "Derek Yamamoto",
    initials: "DY",
    phoneMask: "(•••) •••-6671",
    overdue: "10 mo",
    overdueDays: 305,
    lastVisit: "Jul 2, 2025",
    reason: "Hygiene recall",
    stage: "ai_working",
    nextStep: "Asking availability",
    activity: "Patient replied · 6m ago",
    value: 280,
  },
  {
    id: "p-lena",
    name: "Lena Brooks",
    initials: "LB",
    phoneMask: "(•••) •••-2287",
    overdue: "13 mo",
    overdueDays: 396,
    lastVisit: "Apr 5, 2025",
    reason: "Hygiene recall",
    stage: "closed",
    nextStep: "No reply after 2 nudges",
    activity: "Auto-closed · 2 days ago",
    value: 280,
  },
  {
    id: "p-sam",
    name: "Sam Aldridge",
    initials: "SA",
    phoneMask: "(•••) •••-4451",
    overdue: "6 mo",
    overdueDays: 188,
    lastVisit: "Nov 3, 2025",
    reason: "Hygiene recall",
    stage: "not_started",
    nextStep: "Start outreach",
    activity: "—",
    value: 280,
  },
  {
    id: "p-chloe",
    name: "Chloe Reinhardt",
    initials: "CR",
    phoneMask: "(•••) •••-8809",
    overdue: "9 mo",
    overdueDays: 268,
    lastVisit: "Aug 18, 2025",
    reason: "Treatment plan: 1 filling",
    stage: "booked",
    nextStep: "Booked Thu Nov 20 · 9:00am",
    activity: "Skrypt AI booked the slot · 4h ago",
    value: 320,
  },
  {
    id: "p-omar",
    name: "Omar Castellano",
    initials: "OC",
    phoneMask: "(•••) •••-1190",
    overdue: "7 mo",
    overdueDays: 219,
    lastVisit: "Sep 28, 2025",
    reason: "Hygiene recall",
    stage: "needs_you",
    handoff: "asked_human",
    nextStep: "Patient wants to talk to staff",
    activity: "Patient asked for a human · 1h ago",
    value: 280,
  },
];

// Conversation transcripts per patient. Authors: 'staff' | 'patient' | 'ai'.
// Inline 'event' rows describe AI autonomous actions.
const THREADS = {
  "p-rachel": {
    plan: {
      goal: "Book a hygiene cleaning",
      status: "Active — confirming time",
      next: "Will follow up tomorrow 10:00 AM if no reply",
      escalate: "If patient asks a clinical, billing or off-script question",
    },
    messages: [
      { kind: "msg", who: "staff", author: "Maria Chen", time: "Yesterday 4:12 PM",
        text: "Hi Rachel — Maria from Clearstone Dental. Noticed it's been a while since your last cleaning, hope you're doing well! Want me to find you a time?" },
      { kind: "msg", who: "patient", author: "Rachel Moore", time: "Yesterday 5:48 PM",
        text: "Oh hey! Yeah I keep meaning to schedule, been busy. What've you got?" },
      { kind: "event", text: "Skrypt AI took over the conversation" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Yesterday 5:49 PM",
        text: "Totally understand! I'm Skrypt AI, Clearstone's automated scheduling assistant — happy to find a time. Are mornings or afternoons usually easier for you?" },
      { kind: "msg", who: "patient", author: "Rachel Moore", time: "Yesterday 7:02 PM",
        text: "afternoons mostly, after 2 if possible" },
      { kind: "event", text: "Skrypt AI checked Dr. Chen's hygiene schedule for the next 10 business days" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Yesterday 7:02 PM",
        text: "Got it. We have Tue Nov 18 at 2:30pm or Thu Nov 20 at 3:00pm with Dr. Chen — either work?" },
      { kind: "msg", who: "patient", author: "Rachel Moore", time: "Today 9:14 AM",
        text: "tues works 🙏" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Today 9:14 AM",
        text: "Perfect. Holding Tue Nov 18 at 2:30pm for a hygiene cleaning with Dr. Chen — confirming now." },
    ],
    pending: { kind: "msg", who: "ai", author: "Skrypt AI", time: "in ~30s", draft: true,
      text: "You're booked for Tue Nov 18 at 2:30 PM with Dr. Chen. We'll text a reminder 48h before. See you then!" },
  },

  "p-tobias": {
    plan: {
      goal: "Book treatment plan: 2 fillings",
      status: "Paused — handed off to staff",
      next: "Awaiting Maria's reply",
      escalate: "Patient asked about insurance coverage",
    },
    messages: [
      { kind: "msg", who: "staff", author: "Maria Chen", time: "Today 10:14 AM",
        text: "Hi Tobias — Maria from Clearstone. You had two fillings on your plan from October, want to get them on the books?" },
      { kind: "msg", who: "patient", author: "Tobias Grant", time: "Today 10:31 AM",
        text: "yeah probably should. quick q — does my insurance still cover those? I switched jobs in March and have a new plan now" },
      { kind: "event", text: "Skrypt AI detected an insurance question — outside scope" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Today 10:31 AM",
        text: "Great question! I can't verify insurance benefits myself — Maria from our team will hop in to check that for you. One sec." },
      { kind: "event", text: "Handed off to Maria · reason: off-script question" },
    ],
  },

  "p-marcus": {
    plan: {
      goal: "Book crown follow-up",
      status: "Active — awaiting reply",
      next: "Will close as no-response on Wed May 13 if no reply",
      escalate: "If patient asks a clinical, billing or off-script question",
    },
    messages: [
      { kind: "msg", who: "staff", author: "Maria Chen", time: "Tue 3:40 PM",
        text: "Hi Marcus — Maria from Clearstone. Just checking in on the crown — Dr. Chen wanted to see you for a quick follow-up. Want me to set something up?" },
      { kind: "msg", who: "patient", author: "Marcus Liu", time: "Tue 8:11 PM",
        text: "sure, sometime in the next couple weeks" },
      { kind: "event", text: "Skrypt AI took over the conversation" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Tue 8:11 PM",
        text: "Sounds good! What time of day usually works best — mornings, afternoons, or evenings?" },
      { kind: "event", text: "Skrypt AI sent a nudge · 48h with no reply" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Today 12:30 PM",
        text: "Hi Marcus, just bumping this — let me know what time of day works and I'll find a slot." },
    ],
  },

  "p-eve":   { plan: null, messages: [] },
  "p-priya": {
    plan: {
      goal: "Book a hygiene cleaning",
      status: "Resolved — booked",
      next: "Reminder 48h before appointment",
      escalate: "—",
    },
    messages: [
      { kind: "msg", who: "staff", author: "Maria Chen", time: "Yesterday 11:02 AM",
        text: "Hi Priya — Maria from Clearstone. You're due for a cleaning, want me to find a time?" },
      { kind: "msg", who: "patient", author: "Priya Shah", time: "Yesterday 11:40 AM", text: "yes please!" },
      { kind: "event", text: "Skrypt AI took over the conversation" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Yesterday 11:40 AM",
        text: "Great! Mornings or afternoons easier for you?" },
      { kind: "msg", who: "patient", author: "Priya Shah", time: "Yesterday 12:08 PM", text: "afternoon" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Yesterday 12:08 PM",
        text: "How about Tue Nov 18 at 2:30pm with Dr. Chen?" },
      { kind: "msg", who: "patient", author: "Priya Shah", time: "Yesterday 1:22 PM", text: "perfect" },
      { kind: "event", text: "Skrypt AI booked Tue Nov 18, 2:30 PM — Hygiene with Dr. Chen" },
      { kind: "msg", who: "ai", author: "Skrypt AI", time: "Yesterday 1:22 PM",
        text: "You're booked for Tue Nov 18 at 2:30pm with Dr. Chen. Reminder 48h before. See you then!" },
    ],
  },
};

const METRICS = {
  overdue: 247,
  inOutreach: 38,
  bookedThisMonth: { count: 14, value: 11420 },
  needsYou: 3,
  trend: [4,6,3,8,9,5,11,7,9,12,10,14], // bookings/wk last 12 wks
};

window.STAGE = STAGE;
window.HANDOFF = HANDOFF;
window.PATIENTS = PATIENTS;
window.THREADS = THREADS;
window.METRICS = METRICS;
